//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptgSmsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AptgSmsServiceReference.SMSSoap")]
    public interface SMSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getConnectionResponse> getConnectionAsync(AptgSmsServiceReference.getConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/closeConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.closeConnectionResponse> closeConnectionAsync(AptgSmsServiceReference.closeConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendSMSResponse> sendSMSAsync(AptgSmsServiceReference.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendMessageResponse> sendMessageAsync(AptgSmsServiceReference.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendParamSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendParamSMSResponse> sendParamSMSAsync(AptgSmsServiceReference.sendParamSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eraseBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.eraseBookingResponse> eraseBookingAsync(AptgSmsServiceReference.eraseBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getDeliveryStatusResponse> getDeliveryStatusAsync(AptgSmsServiceReference.getDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getCreditResponse> getCreditAsync(AptgSmsServiceReference.getCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFreePhoneCallinLog", ReplyAction="*")]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getFreePhoneCallinLogResponse> getFreePhoneCallinLogAsync(AptgSmsServiceReference.getFreePhoneCallinLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getConnectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getConnection", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getConnectionRequestBody Body;
        
        public getConnectionRequest()
        {
        }
        
        public getConnectionRequest(AptgSmsServiceReference.getConnectionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getConnectionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getConnectionRequestBody()
        {
        }
        
        public getConnectionRequestBody(string userID, string password)
        {
            this.userID = userID;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getConnectionResponseBody Body;
        
        public getConnectionResponse()
        {
        }
        
        public getConnectionResponse(AptgSmsServiceReference.getConnectionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getConnectionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getConnectionResult;
        
        public getConnectionResponseBody()
        {
        }
        
        public getConnectionResponseBody(string getConnectionResult)
        {
            this.getConnectionResult = getConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnection", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.closeConnectionRequestBody Body;
        
        public closeConnectionRequest()
        {
        }
        
        public closeConnectionRequest(AptgSmsServiceReference.closeConnectionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeConnectionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        public closeConnectionRequestBody()
        {
        }
        
        public closeConnectionRequestBody(string sessionKey)
        {
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.closeConnectionResponseBody Body;
        
        public closeConnectionResponse()
        {
        }
        
        public closeConnectionResponse(AptgSmsServiceReference.closeConnectionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class closeConnectionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string closeConnectionResult;
        
        public closeConnectionResponseBody()
        {
        }
        
        public closeConnectionResponseBody(string closeConnectionResult)
        {
            this.closeConnectionResult = closeConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendSMSRequestBody Body;
        
        public sendSMSRequest()
        {
        }
        
        public sendSMSRequest(AptgSmsServiceReference.sendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sendTime;
        
        public sendSMSRequestBody()
        {
        }
        
        public sendSMSRequestBody(string sessionKey, string subject, string content, string mobile, string sendTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.content = content;
            this.mobile = mobile;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendSMSResponseBody Body;
        
        public sendSMSResponse()
        {
        }
        
        public sendSMSResponse(AptgSmsServiceReference.sendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendSMSResult;
        
        public sendSMSResponseBody()
        {
        }
        
        public sendSMSResponseBody(string sendSMSResult)
        {
            this.sendSMSResult = sendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendMessageRequestBody Body;
        
        public sendMessageRequest()
        {
        }
        
        public sendMessageRequest(AptgSmsServiceReference.sendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sendTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string retryTime;
        
        public sendMessageRequestBody()
        {
        }
        
        public sendMessageRequestBody(string sessionKey, string subject, string content, string mobile, string sendTime, string retryTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.content = content;
            this.mobile = mobile;
            this.sendTime = sendTime;
            this.retryTime = retryTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendMessageResponseBody Body;
        
        public sendMessageResponse()
        {
        }
        
        public sendMessageResponse(AptgSmsServiceReference.sendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMessageResult;
        
        public sendMessageResponseBody()
        {
        }
        
        public sendMessageResponseBody(string sendMessageResult)
        {
            this.sendMessageResult = sendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendParamSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendParamSMS", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendParamSMSRequestBody Body;
        
        public sendParamSMSRequest()
        {
        }
        
        public sendParamSMSRequest(AptgSmsServiceReference.sendParamSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendParamSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contentXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sendTime;
        
        public sendParamSMSRequestBody()
        {
        }
        
        public sendParamSMSRequestBody(string sessionKey, string subject, string contentXML, string sendTime)
        {
            this.sessionKey = sessionKey;
            this.subject = subject;
            this.contentXML = contentXML;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendParamSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendParamSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.sendParamSMSResponseBody Body;
        
        public sendParamSMSResponse()
        {
        }
        
        public sendParamSMSResponse(AptgSmsServiceReference.sendParamSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendParamSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendParamSMSResult;
        
        public sendParamSMSResponseBody()
        {
        }
        
        public sendParamSMSResponseBody(string sendParamSMSResult)
        {
            this.sendParamSMSResult = sendParamSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eraseBookingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eraseBooking", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.eraseBookingRequestBody Body;
        
        public eraseBookingRequest()
        {
        }
        
        public eraseBookingRequest(AptgSmsServiceReference.eraseBookingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eraseBookingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string batchID;
        
        public eraseBookingRequestBody()
        {
        }
        
        public eraseBookingRequestBody(string sessionKey, string batchID)
        {
            this.sessionKey = sessionKey;
            this.batchID = batchID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eraseBookingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eraseBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.eraseBookingResponseBody Body;
        
        public eraseBookingResponse()
        {
        }
        
        public eraseBookingResponse(AptgSmsServiceReference.eraseBookingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eraseBookingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eraseBookingResult;
        
        public eraseBookingResponseBody()
        {
        }
        
        public eraseBookingResponseBody(string eraseBookingResult)
        {
            this.eraseBookingResult = eraseBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryStatus", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getDeliveryStatusRequestBody Body;
        
        public getDeliveryStatusRequest()
        {
        }
        
        public getDeliveryStatusRequest(AptgSmsServiceReference.getDeliveryStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string batchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageNo;
        
        public getDeliveryStatusRequestBody()
        {
        }
        
        public getDeliveryStatusRequestBody(string sessionKey, string batchID, string pageNo)
        {
            this.sessionKey = sessionKey;
            this.batchID = batchID;
            this.pageNo = pageNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDeliveryStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDeliveryStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getDeliveryStatusResponseBody Body;
        
        public getDeliveryStatusResponse()
        {
        }
        
        public getDeliveryStatusResponse(AptgSmsServiceReference.getDeliveryStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDeliveryStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDeliveryStatusResult;
        
        public getDeliveryStatusResponseBody()
        {
        }
        
        public getDeliveryStatusResponseBody(string getDeliveryStatusResult)
        {
            this.getDeliveryStatusResult = getDeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCredit", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getCreditRequestBody Body;
        
        public getCreditRequest()
        {
        }
        
        public getCreditRequest(AptgSmsServiceReference.getCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        public getCreditRequestBody()
        {
        }
        
        public getCreditRequestBody(string sessionKey)
        {
            this.sessionKey = sessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getCreditResponseBody Body;
        
        public getCreditResponse()
        {
        }
        
        public getCreditResponse(AptgSmsServiceReference.getCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCreditResult;
        
        public getCreditResponseBody()
        {
        }
        
        public getCreditResponseBody(string getCreditResult)
        {
            this.getCreditResult = getCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFreePhoneCallinLogRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFreePhoneCallinLog", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getFreePhoneCallinLogRequestBody Body;
        
        public getFreePhoneCallinLogRequest()
        {
        }
        
        public getFreePhoneCallinLogRequest(AptgSmsServiceReference.getFreePhoneCallinLogRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFreePhoneCallinLogRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string activityID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string beginDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pageNo;
        
        public getFreePhoneCallinLogRequestBody()
        {
        }
        
        public getFreePhoneCallinLogRequestBody(string sessionKey, string activityID, string beginDate, string endDate, string pageNo)
        {
            this.sessionKey = sessionKey;
            this.activityID = activityID;
            this.beginDate = beginDate;
            this.endDate = endDate;
            this.pageNo = pageNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFreePhoneCallinLogResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFreePhoneCallinLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public AptgSmsServiceReference.getFreePhoneCallinLogResponseBody Body;
        
        public getFreePhoneCallinLogResponse()
        {
        }
        
        public getFreePhoneCallinLogResponse(AptgSmsServiceReference.getFreePhoneCallinLogResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFreePhoneCallinLogResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFreePhoneCallinLogResult;
        
        public getFreePhoneCallinLogResponseBody()
        {
        }
        
        public getFreePhoneCallinLogResponseBody(string getFreePhoneCallinLogResult)
        {
            this.getFreePhoneCallinLogResult = getFreePhoneCallinLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SMSSoapChannel : AptgSmsServiceReference.SMSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<AptgSmsServiceReference.SMSSoap>, AptgSmsServiceReference.SMSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), SMSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getConnectionResponse> AptgSmsServiceReference.SMSSoap.getConnectionAsync(AptgSmsServiceReference.getConnectionRequest request)
        {
            return base.Channel.getConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.getConnectionResponse> getConnectionAsync(string userID, string password)
        {
            AptgSmsServiceReference.getConnectionRequest inValue = new AptgSmsServiceReference.getConnectionRequest();
            inValue.Body = new AptgSmsServiceReference.getConnectionRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.password = password;
            return ((AptgSmsServiceReference.SMSSoap)(this)).getConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.closeConnectionResponse> AptgSmsServiceReference.SMSSoap.closeConnectionAsync(AptgSmsServiceReference.closeConnectionRequest request)
        {
            return base.Channel.closeConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.closeConnectionResponse> closeConnectionAsync(string sessionKey)
        {
            AptgSmsServiceReference.closeConnectionRequest inValue = new AptgSmsServiceReference.closeConnectionRequest();
            inValue.Body = new AptgSmsServiceReference.closeConnectionRequestBody();
            inValue.Body.sessionKey = sessionKey;
            return ((AptgSmsServiceReference.SMSSoap)(this)).closeConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendSMSResponse> AptgSmsServiceReference.SMSSoap.sendSMSAsync(AptgSmsServiceReference.sendSMSRequest request)
        {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.sendSMSResponse> sendSMSAsync(string sessionKey, string subject, string content, string mobile, string sendTime)
        {
            AptgSmsServiceReference.sendSMSRequest inValue = new AptgSmsServiceReference.sendSMSRequest();
            inValue.Body = new AptgSmsServiceReference.sendSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            return ((AptgSmsServiceReference.SMSSoap)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendMessageResponse> AptgSmsServiceReference.SMSSoap.sendMessageAsync(AptgSmsServiceReference.sendMessageRequest request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.sendMessageResponse> sendMessageAsync(string sessionKey, string subject, string content, string mobile, string sendTime, string retryTime)
        {
            AptgSmsServiceReference.sendMessageRequest inValue = new AptgSmsServiceReference.sendMessageRequest();
            inValue.Body = new AptgSmsServiceReference.sendMessageRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.mobile = mobile;
            inValue.Body.sendTime = sendTime;
            inValue.Body.retryTime = retryTime;
            return ((AptgSmsServiceReference.SMSSoap)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.sendParamSMSResponse> AptgSmsServiceReference.SMSSoap.sendParamSMSAsync(AptgSmsServiceReference.sendParamSMSRequest request)
        {
            return base.Channel.sendParamSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.sendParamSMSResponse> sendParamSMSAsync(string sessionKey, string subject, string contentXML, string sendTime)
        {
            AptgSmsServiceReference.sendParamSMSRequest inValue = new AptgSmsServiceReference.sendParamSMSRequest();
            inValue.Body = new AptgSmsServiceReference.sendParamSMSRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.subject = subject;
            inValue.Body.contentXML = contentXML;
            inValue.Body.sendTime = sendTime;
            return ((AptgSmsServiceReference.SMSSoap)(this)).sendParamSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.eraseBookingResponse> AptgSmsServiceReference.SMSSoap.eraseBookingAsync(AptgSmsServiceReference.eraseBookingRequest request)
        {
            return base.Channel.eraseBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.eraseBookingResponse> eraseBookingAsync(string sessionKey, string batchID)
        {
            AptgSmsServiceReference.eraseBookingRequest inValue = new AptgSmsServiceReference.eraseBookingRequest();
            inValue.Body = new AptgSmsServiceReference.eraseBookingRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            return ((AptgSmsServiceReference.SMSSoap)(this)).eraseBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getDeliveryStatusResponse> AptgSmsServiceReference.SMSSoap.getDeliveryStatusAsync(AptgSmsServiceReference.getDeliveryStatusRequest request)
        {
            return base.Channel.getDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.getDeliveryStatusResponse> getDeliveryStatusAsync(string sessionKey, string batchID, string pageNo)
        {
            AptgSmsServiceReference.getDeliveryStatusRequest inValue = new AptgSmsServiceReference.getDeliveryStatusRequest();
            inValue.Body = new AptgSmsServiceReference.getDeliveryStatusRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.batchID = batchID;
            inValue.Body.pageNo = pageNo;
            return ((AptgSmsServiceReference.SMSSoap)(this)).getDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getCreditResponse> AptgSmsServiceReference.SMSSoap.getCreditAsync(AptgSmsServiceReference.getCreditRequest request)
        {
            return base.Channel.getCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.getCreditResponse> getCreditAsync(string sessionKey)
        {
            AptgSmsServiceReference.getCreditRequest inValue = new AptgSmsServiceReference.getCreditRequest();
            inValue.Body = new AptgSmsServiceReference.getCreditRequestBody();
            inValue.Body.sessionKey = sessionKey;
            return ((AptgSmsServiceReference.SMSSoap)(this)).getCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AptgSmsServiceReference.getFreePhoneCallinLogResponse> AptgSmsServiceReference.SMSSoap.getFreePhoneCallinLogAsync(AptgSmsServiceReference.getFreePhoneCallinLogRequest request)
        {
            return base.Channel.getFreePhoneCallinLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<AptgSmsServiceReference.getFreePhoneCallinLogResponse> getFreePhoneCallinLogAsync(string sessionKey, string activityID, string beginDate, string endDate, string pageNo)
        {
            AptgSmsServiceReference.getFreePhoneCallinLogRequest inValue = new AptgSmsServiceReference.getFreePhoneCallinLogRequest();
            inValue.Body = new AptgSmsServiceReference.getFreePhoneCallinLogRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.activityID = activityID;
            inValue.Body.beginDate = beginDate;
            inValue.Body.endDate = endDate;
            inValue.Body.pageNo = pageNo;
            return ((AptgSmsServiceReference.SMSSoap)(this)).getFreePhoneCallinLogAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://biz2.e8d.tw/aptg/API21/SOAP/SMS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SMSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://biz2.e8d.tw/aptg/API21/SOAP/SMS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SMSSoap,
            
            SMSSoap12,
        }
    }
}
